feat: Ran necessary configuration and the kubernetes deployment in the github workflow

diff --git a/.github/workflows/infra.yaml b/.github/workflows/infra.yaml
--- a/.github/workflows/infra.yaml
+++ b/.github/workflows/infra.yaml
@@ -123,41 +123,76 @@ jobs:
       #   working-directory: ./infra/file-structure/${{github.head_ref}}
   
 
-
-
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v3
-
-
 
       - name: Terraform Init
         run: terraform init 
 
-
-
       - name: Terraform Format
         run: terraform fmt
-
-
 
       - name: Terraform Plan
         run: |
           # terraform force-unlock -force 58438d7c-2335-1f96-ecd7-b198c50ee504
-          # terraform plan -var "environment_name=${{github.head_ref}}" -var "REPOSITORY=oriafo/ha_odoo-18.0_deployment" -ver "REGISTRY=${{ steps.login-ecr.outputs.registry }}" -var "run_number=${{ github.run_number }}" -var "access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "secret_aws_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -out=plan.tfplan
-          terraform plan -var "environment_name=${{github.head_ref}}" -var "access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "secret_aws_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -out=plan.tfplan
-
-
+          #terraform plan -var "environment_name=${{github.head_ref}}" -var "access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "secret_aws_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -out=plan.tfplan
+          terraform plan -var "environment_name=${{github.head_ref}}" -out=plan.tfplan
 
       - name: check for plain.tfplan in this directory
         run: ls -l
 
-      
-
       - name: Terraform Apply 
         #run: terraform apply -var "environment_name=${{github.head_ref}}" -var "REPOSITORY=oriafo/ha_odoo-18.0_deployment" -var "REGISTRY=${{ steps.login-ecr.outputs.registry }}" -var "run_number=${{ github.run_number }}" -var "access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "secret_aws_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -auto-approve
-        run: terraform apply -var "environment_name=${{github.head_ref}}" -var "access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" -var "secret_aws_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" -auto-approve
+        run: terraform apply -var "environment_name=${{github.head_ref}}" -auto-approve
 
-              
+      - name: Check Provisioning Status
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Infrastructure Provisioning failed"
+            exit 1
+          else
+            echo "Infrastructure Provisioning Successful"
+          fi
+
+      - name: Terraform Output to get the Cluster Name
+        run: |
+          terraform output -json > tf_output.json
+          EKS_CLUSTER_NAME=$(jq -r '.eks_cluster_name.value' tf_output.json)
+          if [ -z "$EKS_CLUSTER_NAME" ]; then
+            echo "Error: Cluster not created."
+            exit 1
+          fi
+          echo "EKS_CLUSTER_NAME=$EKS_CLUSTER_NAME" >> $GITHUB_ENV
+          echo "Captured EKS CLUSTER NAME: $EKS_CLUSTER_NAME"
+
+      - name: Check if the Cluster Name was captured
+        if: ${{ env.EKS_CLUSTER_NAME == '' }}
+        run: |
+          echo "Error: Eks Cluster Name is empty. Exiting."
+          exit 1   
+
+      - name: Set up AWS CLI and Kubectl utility
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y unzip
+          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          unzip awscliv2.zip
+          sudo ./aws/install
+          aws --version
+          curl -LO "https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl"
+          chmod +x ./kubectl
+          sudo mv ./kubectl /usr/local/bin/kubectl
+
+      - name: Update kubeconfig for EKS
+        run: |
+          aws eks update-kubeconfig --region us-east-1 --name ${{ env.EKS_CLUSTER_NAME }}
+
+
+      - name: Deploy to Kubernetes
+        run: |
+          kubectl apply -f k8/manifests/sample-app.yaml
+
+      
       - name: Check Deployment Status
         run: |
           if [ $? -ne 0 ]; then
@@ -166,27 +201,6 @@ jobs:
           else
             echo "Deployment Successful"
           fi
-
-        
-      # - name: Set up Kubernetes kubectl
-      #   uses: azure/setup-kubectl@v4
-      #   with:
-      #     kubeconfig: ${{ secrets.KUBERNETES_CREDENTIALS }}  # Load Kubeconfig from GitHub Secrets
-  
-      # - name: Deploy to Kubernetes
-      #   run: |
-      #     kubectl apply -f k8s/odoo-deployment.yml  # Path to your Kubernetes manifest file
-      #     kubectl apply -f k8s/odoo-service.yml      # If you have a service definition
-
-      
-      # - name: Check Deployment Status
-      #   run: |
-      #     if [ $? -ne 0 ]; then
-      #       echo "Deployment failed"
-      #       exit 1
-      #     else
-      #       echo "Deployment Successful"
-      #     fi
 
 
 
@@ -205,116 +219,6 @@ jobs:
 
 
   
-
-
-# name: odoo Infrastructure Provisioning
-
-# on:
-#   pull_request:
-#     branches:
-#       - main                                         # Trigger on pull requests to the main branch
-#       - staging
-#       - dev
-      
-# permissions:
-#   contents: read
-#   id-token: write
-
-# jobs:
-#   Infra_provisioning:
-#     runs-on: ubuntu-latest
-#     environment: ${{github.head_ref}}
-#     defaults:
-#       run:
-#         shell: bash
-#         working-directory: ./infra/file-structure/${{github.head_ref}}
-#     steps:
-#       - name: Checkout code
-#         uses: actions/checkout@v4
-
-#       - name: echo the current branch
-#         run:  |
-#           echo "Current branch is: ${{github.head_ref}}"
-    
-#       - name: Configure AWS Credentials for Development Environment
-#         uses: aws-actions/configure-aws-credentials@v4
-#         with:
-#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-#           aws-region: us-east-1
-
-#       - name: Set profile output
-#         id: check_cfn_stack
-#         run: |
-#           if [[ ${{github.head_ref}}  == "dev" ]]; then
-#             echo "profile=dikodin_profile" >> $GITHUB_OUTPUT 
-#           else
-#             echo "profile=dikodin_production" >> $GITHUB_OUTPUT
-#           fi
-       
-#       - name: Capture Profile Output and Set Environment Variable
-#         run: |
-#           echo "PROFILE=${{steps.check_cfn_stack.outputs.profile}}" >> $GITHUB_ENV  
-#           PROFILE="${{steps.check_cfn_stack.outputs.profile}}"
-#           echo "Using profile: $PROFILE" 
-
-#       - name: Check if CloudFormation stack exists
-#         id: check_stack
-#         run: |
-#           set +e
-#           CFN_STACK_NAME="odoo-backend-${{github.head_ref}}"
-#           aws cloudformation describe-stacks --stack-name $CFN_STACK_NAME --profile "$PROFILE" --region us-east-1 > /dev/null 2>&1
-#           if [ $? -eq 0 ]; then
-#             echo "Stack $CFN_STACK_NAME exists."
-#             echo "stack_exists=true" >> $GITHUB_OUTPUT
-#             echo "Exit: ${{steps.check_cfn_stack.outputs.stack_exists}}" 
-#           else
-#             echo "Stack $CFN_STACK_NAME does not exist."
-#             echo "stack_exists=false" >> $GITHUB_OUTPUT 
-#             # echo "stack_exists=false" >> $GITHUB_OUTPUT
-#             echo "Exit: ${{steps.check_cfn_stack.outputs.stack_exists}}" 
-#           fi
-#           set -e  
-          
-#       - name: Deploy resources if stack does not exist
-#         if: ${{steps.check_cfn_stack.outputs.stack_exists}} == 'false' 
-#         working-directory: ./cfn
-#         run: |
-#           aws cloudformation create-stack --stack-name odoo-backend-${{github.head_ref}} --template-body file://backend.yaml --region us-east-1 --debug
-#           sleep 20
-#       - name: Skip deployment if stack exists
-#         if: ${{steps.check_cfn_stack.outputs.stack_exists}}== 'true' 
-#         run: |
-#           echo "Stack already exists, skipping deployment,"
-#         working-directory: ./infra/file-structure/${{github.head_ref}}
-  
-#       - name: Set up Terraform
-#         uses: hashicorp/setup-terraform@v3
-
-#       - name: Terraform Init
-#         run: terraform init
-
-#       - name: Terraform Format
-#         run: terraform fmt
-
-#       - name: Terraform Plan
-#         run: terraform plan -var "environment_name=${{github.head_ref}}" -out=plan.tfplan 
-
-#       - name: check for plain.tfplan in this directory
-#         run: ls -l
-
-#       - name: Terraform Apply 
-#         run: terraform apply -var "environment_name=${{github.head_ref}}" -auto-approve
-
-#       - name: Check Terraform Status
-#         run: |
-#           if [ $? -ne 0 ]; then
-#             echo "Terraform apply failed"
-#             exit 1
-#           else
-#             echo "Terraform apply succeeded"
-#           fi
-
 
 
 
